program AerOpt
   
    ! Initializing Parameters and Implement Modules  
    use CreateInitialNests
    use GenerateInitialMeshes
    use Toolbox
    use Optimization
    use ReadData
    
    implicit none
    integer :: i, j, k                ! Simple Loop Variables
    
    !type(InputVariablesData) :: IV       ! contains the input variables 

    ! ****User Input****** !
    type InputVariablesData
        
        real :: Ma                      ! Mach number
        real :: xmax                    ! Maximum horizontal displacement of Control Nodes
        real :: ymax                    ! Maximum vertical displacement of Control Nodes
        real :: zmax                    ! Maximum lateral displacement of Control Nodes
        ! 1D: only x considered, 2D: x & y considered, 3D: x, y & z considered
        real :: engFMF                  ! Solver variable - engines Front Mass Flow
        real :: Top2Low                 ! Fraction of Top to Low Nests
        integer :: NoNests              ! Number of Nests (Cuckoo Search)
        integer :: NoCP                 ! Number of Control Points
        integer :: NoDim                ! Number of Dimensions
        integer :: NoG                  ! Number of Generations
        integer :: NoPOMod              ! No of POD Modes considered
        integer :: NoLeviSteps          ! Number of Levy walks per movement
        integer :: NoIter               ! Batch File variable - Number of Iterations    
        logical :: constrain            ! Constrain: Include boundaries of design space for Levy Walk - 1:Yes 0:no
        integer :: delay                ! Delay per check in seconds
        integer :: waitMax              ! maximum waiting time in hours
        real :: Aconst                  ! Levy Flight parameter (determined emperically) 

        character(len=20) :: filename    ! I/O file of initial Meshes for FLITE solver
        character :: runOnCluster       ! Run On Cluster or Run on Engine?
        character :: SystemType         ! Windows('W'), Cluster/QSUB ('Q') or HPCWales/BSUB ('B') System? (Cluster, HPCWales = Linux, Visual Studio = Windows)    
        character(len=20) :: UserName    ! Putty Username
        character(len=20) :: Password    ! Putty Password
        character(len=100) :: defPath    ! defines defaultpath - Clusterpath: 'egnaumann/2DEngInlSim/'
        character(len=3) :: version
        
    end type InputVariablesData

    character(len=10) :: InFolder = 'Input_Data'               ! Input Folder Name
    character(len=11) :: OutFolder = 'Output_Data'             ! Output Folder Name
    integer :: IntSystem                                        ! Length of System command string; used for character variable allocation
    real :: waitTime                                            ! waiting time for Simulation Results
    integer :: jobcheck                                         ! Check Variable for Simulation 
    character(len=:), allocatable :: istr                       ! Number of I/O file
    character(len=21) :: pathWin                                ! Path to Windows preprocessor file
    character(len=:), allocatable :: pathLin_Prepro             ! Path to Linux preprocessor file
    character(len=:), allocatable :: pathLin_Solver             ! Path to Linux Solver file
    character(len=:), allocatable :: strSystem                  ! System Command string for communication with FLITE Solver
    character(len=8) :: date                                    ! Container for current date
    character(len=10) :: time                                   ! Container for current time
    character(len=35) :: newdir                                 ! Name of new folder for a new Solution generated by 2D solver
 
    type(InputVariablesData) :: IV
    
    namelist /InputVariables/ IV
    
    IV%Ma = 0.5  		            ! Mach number
    IV%xmax = 0.00			        ! Maximum horizontal displacement of Control Nodes    
    IV%ymax = 0.02			        ! Maximum vertical displacement of Control Nodes    
    IV%zmax = 0.00			        ! Maximum lateral displacement of Control Nodes    
    IV%engFMF = 1.0			        ! engines Front Mass Flow(Solver variable)
    IV%Top2Low = 0.75		        ! Fraction of Top to Low Cuckoo Nests
    IV%NoNests = 30              	! Number of Nests (Cuckoo Search) 
    IV%NoCP = 7			            ! Number of Control Points 
    IV%NoDim = 2			        ! Number of Dimensions in Space 
    IV%NoG = 5			            ! Number of Generations 
    IV%NoPOMod = -1			        ! No of POD Modes considered 
    IV%NoLeviSteps = 100         	! Number of Levy walks per movement 
    IV%NoIter = -3               	! Batch File variable - Number of Iterations 
    IV%constrain = .TRUE.         	! Constrain: Include boundaries of design space for Levy Walk - 1:Yes 0:no
    IV%delay = 300               	! Sleep Time between check for Simulation Results in seconds
    IV%waitMax = 48			        ! maximum waiting time in hours
    IV%Aconst = 0.01		        ! Levy Flight parameter (determined emperically)
    IV%filename = 'Snapshot'        ! I/O file of initial Meshes for FLITE solver
    IV%runOnCluster = 'Y'           ! Run On Cluster or Run on Engine?
    IV%SystemType = 'Q'             ! Windows('W'), Cluster/QSUB ('Q') or HPCWales/BSUB ('B') System? (Cluster, HPCWales = Linux, Visual Studio = Windows)
    IV%UserName = 'egnaumann'       ! Putty Username
    IV%Password = 'Fleur666'        ! Putty Password
    IV%defPath = 'egnaumann/2DEngInlSim'  ! defines defaultpath - Clusterpath: 'egnaumann/2DEngInlSim/'
    IV%version = '1.3'
    
    open(1,file = InFolder//'/AerOpt_InputParameters.txt')
    read(1,InputVariables)
    close(1)
    
    ! Check xmax, ymax, zmax & NoDim Input
    if (IV%NoDim == 1) then
        if (IV%ymax /= 0 .or. IV%zmax /= 0) then
            print *, 'ymax and/or zmax remain unconsidered in 1 Dimension'
            print *, 'Input any and click enter to continue'
            read(*, *)
        end if
    elseif (IV%NoDim == 2) then
        if (IV%zmax /= 0) then
            print *, 'zmax remains unconsidered in 2 Dimensions'
            print *, 'Input any and click enter to continue'
            read(*, *)
        end if
    end if
    
    ! Automatically generates a random initial number based on time and date
    call RANDOM_SEED
    
    ! Get Time and Date for File and Folder Name creation
    call DATE_AND_TIME(date, time)
    newdir = '2DEngInletSnapshots_'//IV%version//'_'//date(3:8)//'_'//time(1:4)
    

    ! ****Sub-Section: Create Initial Nests for the CFD Solver****** ! 
    ! ***********included in CreateInitialNests module************** !
    print *, 'Start LHS Sampling - Create Initial Nests'
    call SubCreateInitialNests(IV%NoNests, IV%NoDim, IV%NoCP, IV%xmax, IV%ymax, IV%zmax)                !Sampling of initial points/nests via LHC    
    ! Output: InitialNests - Sampling Points for initial Nests
    
    
    ! ****Read Input Data(Fine Mesh, Coarse Mesh, CP Coordinates, Influence Box/Rectangle (IB)**** !
    print *, 'Start Read Data'
    call SubReadData(IV%NoCP, IV%NoDim, InFolder)
    ! Output: Boundf, Coord, Connecf, Coord_CP
    
!!!!!! IMPLEMENT double-check, wether Dimension of file and Input are compliant OR error check while Reading files
    
    ! ****Generate initial Meshes/Snapshots**** !
    allocate(coord_temp(np,IV%NoDim))
    allocate(boundff(nbf,(IV%NoDim+1)))
    boundff(:,1:2) = boundf
    do i = 1, IV%NoNests
        print *, "Generating Mesh", i, "/", IV%NoNests
        coord_temp = coord
        call SubGenerateInitialMeshes(IV%NoDim, IV%NoCP, coord_temp, connecf, boundf, coarse, connecc, Coord_CP,Rect, InitialNests(i,:))
        ! Output: New Coordinates - 30 Snapshots with moved boundaries based on initial nests
        
        call IdentifyBoundaryFlags()
        ! Output: Boundary Matrix incluing flags of adiabatic viscous wall, far field & engine inlet (boundff)
        
!!!!! IMPLEMENT Mesh Quality Test

        ! Determine correct String      
        call DetermineStrLen(istr, i) 
        ! Write Snapshot to File
        call InitSnapshots(trim(IV%filename), istr, coord_temp, boundff, IV%NoDim, OutFolder)
        deallocate (istr)
    end do
    

    ! ****Create Folder Structure for PrePro & Solver Output**** !
    print *, 'Create Directories'
    call createDirectoriesInit(newdir, trim(IV%defPath), InFolder, OutFolder)
    if (IV%SystemType == 'W')   then    ! AerOpt is executed from a Windows machine
                             
        call communicateWin2Lin(trim(IV%Username), trim(IV%Password), 'FileCreateDir.scr', 'psftp')   ! Submits create directory file
            
    else                        ! AerOpt is executed from a Linux machine
                            
        call system('chmod a+x ./FileCreateDir.scr')    
        call system('./FileCreateDir.scr')    ! Submits create directory file
            
    end if
    

    ! ****Call 2D Preprocessor and pass on input parameters**** !
    print *, 'Start Preprocessing'
    if (IV%SystemType == 'Q') then
        allocate(character(len=61) :: pathLin_Prepro)
        pathLin_Prepro = '/eng/cvcluster/egnaumann/2DEngInlSim/PrePro/2DPreProcessorLin'
    else
        allocate(character(len=56) :: pathLin_Prepro)
        pathLin_Prepro = '/home/david.naumann/2DEngInlSim/PrePro/2DPreProcessorLin'
    end if
    pathWin = 'Flite2D\PreProcessing'   
    do i = 1, IV%NoNests
    
        ! Determine correct String      
        call DetermineStrLen(istr, i)
        ! write Inputfile
        call PreProInpFile(trim(IV%filename), istr, InFolder, OutFolder)
        
        if (IV%SystemType == 'W') then
             
            allocate(character(len=29) :: strSystem)
            strSystem = pathWin
            
        else
            
            ! write command (for Linux)
            IntSystem = 10 + len(trim(IV%filename)) + len(istr) + len(pathLin_Prepro)
            allocate(character(len=IntSystem) :: strSystem)
            strSystem = pathLin_Prepro//' > '//trim(IV%filename)//istr//'.outpre'
            
        end if
        print *, 'Preprocessing Snapshot', i
        print *, ' '
        call system(strSystem)   ! System operating command called to activate fortran       
        deallocate (istr)
        deallocate (strSystem)
    
    end do
    print *, 'Finished Preprocessing'
    
    
    ! ****Call 2D FLITE Solver and pass on input parameters**** !
    print *, 'Call FLITE 2D Solver'
    if (IV%SystemType /= 'B') then
        allocate(character(len=55) :: pathLin_Solver)
        pathLin_Solver = '/eng/cvcluster/egnaumann/2DEngInlSim/Solver/2DSolverLin'
    else
        allocate(character(len=50) :: pathLin_Solver)
        pathLin_Solver = '/home/david.naumann/2DEngInlSim/Solver/2DSolverLin'
    end if
    
    do i = 1, IV%NoNests
            
        ! Determine correct String      
        call DetermineStrLen(istr, i)                      
        ! Creates the input file including Solver Parameters and a second file including I/O filenames
        call WriteSolverInpFile(trim(IV%filename), istr, IV%engFMF, IV%Ma, IV%NoIter, newdir, IV%NoNests, trim(IV%defPath), InFolder, OutFolder, IV%SystemType)
        ! writes the batchfile to execute Solver on Cluster
        call writeBatchFile(trim(IV%filename), istr, pathLin_Solver, newdir, IV%SystemType, InFolder, OutFolder)
    
        ! Is AerOpt executed from Linux or Windows?                
        if (IV%SystemType == 'W')   then    ! AerOpt is executed from a Windows machine
            
            ! Transfer Files from Windows Machine onto Cluster
            call transferFilesWin(trim(IV%filename), istr, newdir, trim(IV%defPath), InFolder, OutFolder)            
            call communicateWin2Lin(trim(IV%Username), trim(IV%Password), 'FileCreateDir.scr', 'psftp')
            
            if (IV%runOnCluster == 'Y') then
                call Triggerfile(trim(IV%filename), istr, newdir, trim(IV%defPath), InFolder, IV%SystemType)           ! Triggerfile for submission
            else
                call TriggerFile2(trim(IV%filename), istr, pathLin_Solver)  ! Triggerfile for submission
            end if
                    
            ! Submits Batchfile via Putty
            call communicateWin2Lin(trim(IV%Username), trim(IV%Password), 'Trigger.sh', 'putty')
                
        else    ! AerOpt is executed from a Linux machine
            
            ! Transfer Files in correct folder on Cluster
            call transferFilesLin(trim(IV%filename), istr, newdir, trim(IV%defPath), InFolder, OutFolder)
            call system('chmod a+x ./FileCreateDir.scr')
            call system('./FileCreateDir.scr')
            
            if (IV%runOnCluster == 'Y') then
                call Triggerfile(trim(IV%filename), istr, newdir, trim(IV%defPath), InFolder, IV%SystemType)     ! Triggerfile for submission
            else
                call TriggerFile2(trim(IV%filename), istr, pathLin_Solver)               ! Triggerfile for submission
            end if
            
            ! Submits Batchfile
            call system('chmod a+x ./Trigger.sh')
            call system('./Trigger.sh')
                    
        end if
                
        deallocate(istr) 
                
    end do
    print *, 'Finished Submitting Jobs to FLITE 2D Solver'
    
    ! ****Wait & Check for FLITE Solver Output**** !
    print*, 'Start Sleep'
    jobcheck = 0
    waitTime = 0
    j = 1
    do while (jobcheck==0)
        
        ! Wait Function
        print*, 'Sleep'
        call SleepQQ(IV%delay*1000)
        print*, 'Wake Up - Check ', j
        j = j + 1
        
        ! Check Status of Simulation by checking the existence of all error files
        do i = IV%NoNests, 1, -1
            
            ! Determine correct String      
            call DetermineStrLen(istr, i)
            ! Creates File containing Linux commands to check for last file
            call CheckSimStatus(newdir, trim(IV%filename), istr, IV%SystemType, trim(IV%defPath), InFolder)
            ! Submit File
            if (IV%SystemType == 'W')   then
                call communicateWin2Lin(trim(IV%Username), trim(IV%Password), 'CheckStatus.scr', 'plink')
            else
                call system('chmod a+x ./CheckStatus.scr')
                call system('./CheckStatus.scr')
            end if
            ! Creates File to transfer response from Windows to Linux
            if (IV%SystemType == 'W')   then
                call CheckSimStatus2(newdir, trim(IV%defPath), InFolder)
                call communicateWin2Lin(trim(IV%Username), trim(IV%Password), 'CheckStatus.scr', 'psftp')
            end if
            
            open(1, file='check.txt')
            read(1,*) jobcheck
            close(1)
            deallocate(istr)
            if (jobcheck == 0) EXIT           
            
        end do
        
        waitTime = (IV%delay/3600.0) + waitTime
        if (waitTime > IV%waitMax) then
            STOP 'Cluster Simulation Time exceeded maximum waiting Time'
        end if
        
    end do
    print*, 'End Sleep - Jobs are finished'
    
!!!! Check amount of .rsd files & conversion!
    
    ! ****Optimize Mesh by the help of Cuckoo Search and POD**** !
    print *, 'Start Optmization'
    call SubOptimization(IV%NoNests, IV%NoCP, IV%NoDim, cond, InitialNests, MxDisp_Move, np, IV%xmax, IV%Ma, IV%Top2Low, IV%Aconst, IV%NoPOMod, IV%NoLeviSteps, IV%NoG, IV%constrain)
    ! Output: Optimized mesh via Cuckoo Search and POD
    
    
    ! ****Generate Optimum Mesh and Safe in file**** !
    coord_temp = coord
    call SubGenerateInitialMeshes(IV%NoDim, IV%NoCP, coord_temp, connecf, boundf, coarse, connecc, Coord_CP, Rect, NestOpt)
    ! Output: Optimum Coordinates - 1 Mesh with moved boundaries based on optimum Control Point Coordinates
    
    ! Safe Optimum Geometry in Text File
    open(99, file= OutFolder//'/OptimumMesh.txt')         
    write(99,'(1I8)') np
    write(99,'(1I8)') ne
    write(99,'(2f12.7)') transpose(coord_temp)
11  format(3I8)
    close(99)
    
    end program AerOpt