#!/bin/bash --login
#SBATCH --job-name=GeomBatch
#SBATCH -o output.%J
#SBATCH --error=error.%J
#SBATCH -n 10
#maximum job time in D-HH:MM
#SBATCH -t 48:00:00
#SBATCH --mem-per-cpu=4000
module purge
module load parallel
srun="srun -n1 -N1 --exclusive"
parallel="parallel -N 1 --delay .2 -j $SLURM_NTASKS --joblog parallel_joblog --resume"
$parallel "$srun --input=/home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry{1}/SolverInput{1}.sh /home/ben.evans/codes/AerOpt_August2018/Executables/Solver_2D" ::: {1..10}
 
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry1/Geometry1.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry1.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry1/Geometry1.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry1.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry2/Geometry2.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry2.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry2/Geometry2.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry2.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry3/Geometry3.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry3.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry3/Geometry3.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry3.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry4/Geometry4.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry4.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry4/Geometry4.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry4.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry5/Geometry5.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry5.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry5/Geometry5.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry5.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry6/Geometry6.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry6.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry6/Geometry6.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry6.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry7/Geometry7.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry7.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry7/Geometry7.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry7.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry8/Geometry8.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry8.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry8/Geometry8.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry8.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry9/Geometry9.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry9.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry9/Geometry9.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry9.unk
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry10/Geometry10.rsd /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry10.rsd
mv /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Mesh_Data/Geometry10/Geometry10.unk /home/ben.evans/codes/AerOpt_August2018/AerOpt2D_3.1_180822_1108/Solver_Data/Geometry10.unk
